language: node_js
node_js:
  - "7"
before_install: 
  - echo "Installing modules"
install: 
  - npm install
jobs:
  include:
    - stage: npm release
      node_js: "7"
      script: echo "deploying to npm ..."
      before_deploy: cd npm_module
      deploy:
        provider: npm
        email: nandubatchu@gmail.com
        api_key: $NPM_TOKEN
        on:
          branch: master
          tags: true
    - stage: gh-pages push
      script: npm run-script build
      script: echo "build finished!"
      script: echo "pushing changes to gh-pages ..."
      deploy:
        provider: pages
        local-dir: docs
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        on:
          branch: master